version: '3.7'
services:
  postgres:
    container_name: fms_db
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=fms_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fms
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./sql/seeder.sql:/docker-entrypoint-initdb.d/seeder.sql
