version: '3.7'
services:
  postgres:
    container_name: fms_db
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=fms_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fms
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./sql/seeder.sql:/docker-entrypoint-initdb.d/seeder.sql
  frontend:
    container_name: fms_web
    build:
      context: ./ui
      dockerfile: dockerfile.ui
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/usr/src/app
  backend:
    container_name: fms_api
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - "8181:8181"
    volumes:
      - ./api:/usr/src/app
