import Head from 'next/head';
import React, { FC } from 'react';

export const Layout: FC = () => (
  <Head>
    <title>Fun Management System | Outdoor Fun Network</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
)

export default Layout;
